### PR TITLE
fixed incorrect display message in version issue #111

### LINKED ISSUE #111: incorrect display message in version subcommand, when using custom build.
When using a custom built openebs ctl, the version command shows the following:

```
You are using an older version (dev) of cli, latest available version is: v0.3.1
```

When using the dev version. The above message should change to:
```
You are using development version of cli, latest released version is: v0.3.1
```

### PR DESCRIPTION
**Pull request by Amishakumari544**
Fixed the message display issue #111

### CODE REVIEW

File: cmd/version/version.go [hunk 1]
```diff
@@ -119,9 +119,12 @@ func checkForLatestVersion(currVersion string) {
...
 	latestVersion := data["spec"].(map[string]interface{})["version"].(string)
 	if !isLatestVersion(currVersion, latestVersion) {
-		// The seperator for the error print
 		fmt.Println()
-		fmt.Printf("You are using an older version (%s) of cli, latest available version is: %s", currVersion, latestVersion)
+		if currVersion == "dev" {
+			fmt.Println("You are using development version of cli, latest released version is: " + latestVersion)
+			return
+		}
+			fmt.Println("You are using an older version of cli, latest available version is: " + currVersion, latestVersion)
```
Comment (vharsh) [inline cmd/version/version.go]:
```suggestion
		if currVersion == "dev" {
			fmt.Println("You are using development version of cli, latest released version is: " + latestVersion)
			return
		}
		fmt.Println("You are using an older version of cli, latest available version is: " + latestVersion)
```

**Review by vharsh — APPROVED** [review]
lgtm

**Comment by vharsh** [comment]
@Amishakumari544 merged this one, congrats on your first PR. Please sign your commits from now on.
